# Generated by Django 6.0.5 on 2026-05-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditor", "0004_analista_data_tools"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Anexo opcional (ex.: tabela carregada): kind, filename, columns, rows, dtypes, sample.",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="toolcall",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
