# Generated by Django 6.0.5 on 2026-06-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditor", "0008_azure_openai_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolcall",
            name="nested_tool_calls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tool calls do sub-agente quando esta tool é call_agent.",
            ),
        ),
    ]
