# Generated by Django 6.0.5 on 2026-06-05 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditor", "0016_gerar_fluxograma"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Meu agente", max_length=80)),
                ("icon", models.CharField(default="🤖", max_length=8)),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Prompt do usuário. Combinado por trás com boas práticas + guardrails.",
                    ),
                ),
                ("model", models.CharField(default="gpt-4o", max_length=80)),
                ("temperature", models.FloatField(default=0.7)),
                (
                    "tools_enabled",
                    models.JSONField(
                        default=list,
                        help_text="Lista de slugs de tools habilitadas para este agente da sessão.",
                    ),
                ),
                (
                    "guardrails",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Regras/limites que o agente deve sempre respeitar.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_agent",
                        to="auditor.conversation",
                    ),
                ),
            ],
        ),
    ]
