# Generated by Django 6.0.5 on 2026-07-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0030_appsettings_massiva_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='input_tokens',
            field=models.IntegerField(default=0, help_text='Tokens de entrada consumidos nesta mensagem.'),
        ),
        migrations.AddField(
            model_name='message',
            name='output_tokens',
            field=models.IntegerField(default=0, help_text='Tokens de saída gerados nesta mensagem.'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
