# Generated by Django 5.2.17 on 2026-08-24 01:55

import django.db.models.deletion
from django.db import migrations, models


def create_initial_revisions(apps, _schema_editor):
    Playbook = apps.get_model("auditor", "Playbook")
    PlaybookRevision = apps.get_model("auditor", "PlaybookRevision")
    for playbook in Playbook.objects.all().iterator():
        PlaybookRevision.objects.get_or_create(
            playbook_id=playbook.id,
            version=playbook.version,
            defaults={
                "snapshot": {
                    "id": playbook.id,
                    "name": playbook.name,
                    "description": playbook.description,
                    "icon": playbook.icon,
                    "status": playbook.status,
                    "version": playbook.version,
                    "nodes": playbook.nodes or [],
                    "edges": playbook.edges or [],
                    "suggestions": playbook.suggestions or [],
                    "execution_policy": playbook.execution_policy or {},
                }
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0038_execution_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='execution_policy',
            field=models.JSONField(blank=True, default=dict, help_text='Política Codex-native: síntese final, confirmação por etapa e comportamento em caso de falha.'),
        ),
        migrations.AddField(
            model_name='playbook',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='playbook',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PlaybookRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='auditor.playbook')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('playbook', 'version'), name='unique_playbook_revision_version')],
            },
        ),
        migrations.RunPython(create_initial_revisions, migrations.RunPython.noop),
    ]
